# Generated by Django 3.2.5 on 2022-01-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
