# Generated by Django 3.2.5 on 2022-01-16 15:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0002_problem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='input',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
