# Generated by Django 3.2.5 on 2022-01-17 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('robo', '0003_auto_20220116_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='users_can_see',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('cpp', 'C++')], max_length=20)),
                ('source', models.TextField()),
                ('time', models.PositiveIntegerField(default=0)),
                ('memory', models.PositiveIntegerField(default=0)),
                ('errors', models.TextField(blank=True, null=True)),
                ('verdict', models.CharField(default='Waiting', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='robo.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
