# Generated by Django 3.2.5 on 2022-01-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0004_auto_20220117_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='time',
            field=models.FloatField(),
        ),
    ]
