# Generated by Django 3.2.5 on 2022-01-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0005_alter_problem_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='time',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
