# Generated by Django 3.2.5 on 2022-01-17 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('robo', '0006_alter_problem_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='users_can_see',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
