# Generated by Django 3.2.5 on 2022-01-19 06:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('robo', '0007_auto_20220117_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('boshlanmagan', 'Boshlanmagan'), ('otkazilmoqda', "O'tkazilmoqda"), ('tugagan', 'Tugagan')], max_length=20)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('langs', models.ManyToManyField(to='robo.ProgrammingLanguage')),
                ('participants', models.ManyToManyField(related_name='participated_contests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
