# Generated by Django 3.2.5 on 2022-01-19 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('robo', '0009_contestproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='robo.contest'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='participated_contests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('boshlanmagan', 'Boshlanmagan'), ('otkazilmoqda', "O'tkazilmoqda"), ('tugagan', 'Tugagan')], default='boshlanmagan', max_length=20),
        ),
    ]
