# Generated by Django 3.2.5 on 2022-01-19 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('robo', '0010_auto_20220119_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='contest_problem',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G'), ('h', 'H'), ('i', 'I'), ('j', 'J'), ('k', 'K'), ('l', 'L'), ('m', 'M'), ('n', 'N'), ('o', 'O'), ('p', 'P'), ('q', 'Q'), ('r', 'R'), ('s', 'S'), ('t', 'T'), ('u', 'U'), ('v', 'V'), ('w', 'W'), ('x', 'X'), ('y', 'Y'), ('z', 'Z')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ContestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.SmallIntegerField(default=0)),
                ('B', models.SmallIntegerField(default=0)),
                ('C', models.SmallIntegerField(default=0)),
                ('D', models.SmallIntegerField(default=0)),
                ('E', models.SmallIntegerField(default=0)),
                ('F', models.SmallIntegerField(default=0)),
                ('G', models.SmallIntegerField(default=0)),
                ('H', models.SmallIntegerField(default=0)),
                ('I', models.SmallIntegerField(default=0)),
                ('J', models.SmallIntegerField(default=0)),
                ('K', models.SmallIntegerField(default=0)),
                ('L', models.SmallIntegerField(default=0)),
                ('M', models.SmallIntegerField(default=0)),
                ('N', models.SmallIntegerField(default=0)),
                ('O', models.SmallIntegerField(default=0)),
                ('P', models.SmallIntegerField(default=0)),
                ('Q', models.SmallIntegerField(default=0)),
                ('R', models.SmallIntegerField(default=0)),
                ('S', models.SmallIntegerField(default=0)),
                ('T', models.SmallIntegerField(default=0)),
                ('U', models.SmallIntegerField(default=0)),
                ('V', models.SmallIntegerField(default=0)),
                ('W', models.SmallIntegerField(default=0)),
                ('X', models.SmallIntegerField(default=0)),
                ('Y', models.SmallIntegerField(default=0)),
                ('Z', models.SmallIntegerField(default=0)),
                ('A_time', models.DateTimeField(blank=True, null=True)),
                ('B_time', models.DateTimeField(blank=True, null=True)),
                ('C_time', models.DateTimeField(blank=True, null=True)),
                ('D_time', models.DateTimeField(blank=True, null=True)),
                ('E_time', models.DateTimeField(blank=True, null=True)),
                ('F_time', models.DateTimeField(blank=True, null=True)),
                ('G_time', models.DateTimeField(blank=True, null=True)),
                ('H_time', models.DateTimeField(blank=True, null=True)),
                ('I_time', models.DateTimeField(blank=True, null=True)),
                ('J_time', models.DateTimeField(blank=True, null=True)),
                ('K_time', models.DateTimeField(blank=True, null=True)),
                ('L_time', models.DateTimeField(blank=True, null=True)),
                ('M_time', models.DateTimeField(blank=True, null=True)),
                ('N_time', models.DateTimeField(blank=True, null=True)),
                ('O_time', models.DateTimeField(blank=True, null=True)),
                ('P_time', models.DateTimeField(blank=True, null=True)),
                ('Q_time', models.DateTimeField(blank=True, null=True)),
                ('R_time', models.DateTimeField(blank=True, null=True)),
                ('S_time', models.DateTimeField(blank=True, null=True)),
                ('T_time', models.DateTimeField(blank=True, null=True)),
                ('U_time', models.DateTimeField(blank=True, null=True)),
                ('V_time', models.DateTimeField(blank=True, null=True)),
                ('W_time', models.DateTimeField(blank=True, null=True)),
                ('X_time', models.DateTimeField(blank=True, null=True)),
                ('Y_time', models.DateTimeField(blank=True, null=True)),
                ('Z_time', models.DateTimeField(blank=True, null=True)),
                ('solved_problems_count', models.PositiveSmallIntegerField(default=0)),
                ('ball', models.PositiveSmallIntegerField(default=0)),
                ('penalty', models.PositiveIntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='robo.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
