# Generated by Django 3.2.5 on 2022-01-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0011_auto_20220119_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestproblem',
            name='name',
        ),
    ]
