# Generated by Django 3.2.5 on 2022-01-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0012_remove_contestproblem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='contest_problem',
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='name',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G'), ('h', 'H'), ('i', 'I'), ('j', 'J'), ('k', 'K'), ('l', 'L'), ('m', 'M'), ('n', 'N'), ('o', 'O'), ('p', 'P'), ('q', 'Q'), ('r', 'R'), ('s', 'S'), ('t', 'T'), ('u', 'U'), ('v', 'V'), ('w', 'W'), ('x', 'X'), ('y', 'Y'), ('z', 'Z')], max_length=10, null=True),
        ),
    ]
